### ISSUE TITLE
Fix orbit caching issues

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#233] opened 2019-01-09 15:49 UTC
After an upgrade or platform reinstall, orbit fails to load. The only way to get it back is to clear cache or use incognito.

**Comment by ryw** [comment] 2019-02-03 14:44
Another customer:

```
Howdy all, I get a blank screen when I hit app.astro.xxx.io
Ah I think it has something to do with cookies.
Works in an incognito browser.
```

**Comment by schnie** [comment] 2019-02-06 14:32
I think we just need to add some kind of hash to some filenames to cachebust or something along those lines.

**Comment by schnie** [comment] 2019-04-29 18:59
@andriisoldatenko thinking this maybe caused by the `index.html` file being cached. Wondering if we could set some caching headers via nginx to help solve. Any other ideas?

https://github.com/astronomer/astronomer/blob/master/docker/platform/orbit-ui/include/nginx.conf

**Comment by andriisoldatenko** [comment] 2019-05-01 13:47
fixed via https://github.com/astronomer/astronomer/pull/298

**Closed** 2019-05-01 14:29 UTC
Labels: area/orbit-ui, kind/bug, priority/urgent
