### ISSUE TITLE
Orbit triggers unexpected and outdated deployments

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#322] opened 2019-05-28 20:07 UTC
Currently, orbit submits too much information to the `updateDeployment` mutation. This can potentially cause problems when a user loads the configure page for a deployment, someone pushes a new tag to the registry asynchronously (updating the running docker tag), then a user updates and saves on the configure page in orbit. Since orbit has the original tag cached and submits it with the `updateDeployment` request, it can unexpectedly roll a user back to a previous deployment.

**Comment by samblackk** [comment] 2019-06-10 16:50
@schnie The solution here is to only push updates to changed values and leave unchanged values alone. Working on a fix for this.

**Comment by schnie** [comment] 2019-07-09 16:18
@samblackk did you come up with anything for this one?

**Comment by samblackk** [comment] 2019-07-09 17:15
@schnie I know the solution just need to get into writing. Prioritizing - expect a PR by EOW or sooner.

**Comment by samblackk** [comment] 2019-07-09 18:04
@schnie PR open!

**Comment by ryw** [comment] 2019-07-17 15:11
Closing this issue, since PR has been merged.

**Comment by andrewhharmon** [comment] 2019-07-30 18:54
I believe I just experienced this issue on cloud-staging. my deployment is running `Astronomer v0.10.0-alpha.5`. my cli vresion was 9.6 if that matters.

**Comment by schnie** [comment] 2019-08-01 04:29
@andrewhharmon can you describe the sequence of steps you took to hit this?

**Comment by paolaperaza** [comment] 2019-08-05 21:19
Looks like we might have just hit this with a customer today, so opening back up in case there's more looking into. Their experience (@andrewhharmon feel free to edit/add in here!):

- Customer started up Airflow locally, Airflow image with latest changes correctly rendered
- Customer pushed up to Cloud
- After several minutes he was still not seeing their new DAG render in the Airflow UI on Cloud
- We saw an error with the Webserver, so the customer bumped up resources in the Orbit UI from 2AU to 5AU on the Webserver
- Pods restarted and were healthy, but the deploy seemingly pushed up the old image. The DAG file was still not there.
- Customer deployed again, and the new image with the additional DAG file was successfully deployed

**Comment by paolaperaza** [comment] 2019-08-06 16:00
@schnie @samblackk FYI this was just reported again by another customer. Not totally sure if it's specific to all orbit configs or if there's any pattern in behavior that's more specific - anything you want me to ask customers who are seeing this?

**Comment by ryw** [comment] 2019-08-06 17:04
@paolaperaza cloud doesn't have this fix yet

**Comment by paolaperaza** [comment] 2019-08-06 17:26
@ryw Ah yes, sorry for false alarm 😬I'll defer to you guys on closing or keeping it open if it's popping up when testing on v0.9.5+

**Comment by ryw** [comment] 2019-08-07 15:41
I am able to reproduce this by changing Extra AU slider on staging.astronomer.io.

1. Load deployment in Astronomer UI
1. Load Airflow UI
1. Deploy new DAG
1. Confirm new DAG is in Airflow UI
1. Without refreshing Astronomer UI, change AU configuration
1. New DAG will disappear in Airflow UI

**Comment by andrewhharmon** [comment] 2019-08-07 21:42
I'm not sure if this is the same issue of different. i have deployment up on 9.6. it's on k8s executor. I upped the extra AU to like 30. i did a deploy. now the AU says 0 when i go back to orbit. 
![image](https://user-images.githubusercontent.com/20602461/62659861-8d37d900-b93a-11e9-8c14-75bd66033d96.png)

whats also weird is the max pods in the metrics tab says 1548... i don't think that's correct? what determines that?
![image](https://user-images.githubusercontent.com/20602461/62659919-b48ea600-b93a-11e9-8ef8-370a6982d2c9.png)

**Comment by schnie** [comment] 2019-08-07 22:04
@ryw created an issue for this today I think.

**Comment by ryw** [comment] 2019-08-09 14:42
@schnie did you resolve this yesterday?

**Comment by schnie** [comment] 2019-08-09 14:57
Testing on datarouter

**Comment by ryw** [comment] 2019-08-09 16:16
Can't reproduce on v0.9.7-rc.2 :)

**Closed by ryw** 2019-08-09 16:16 UTC
Labels: area/houston-api, area/orbit-ui, kind/bug, priority/important
