### ISSUE TITLE
Add support for multiple env files 

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#217] opened 2019-01-09 15:13 UTC

**Comment by ryw** [comment] 2019-01-09 20:32
@benjamingregory I migrated this from Pivotal - you created original issue there, can you drop some notes in issue description for what this work is? And if it's something you're working on, assign this issue to yourself?

**Comment by benjamingregory** [comment] 2019-01-09 23:32
Duplicate of https://github.com/astronomer/astro-cli/issues/159

**Closed by benjamingregory** 2019-01-09 23:32 UTC
Labels: kind/feature, priority/important
