### ISSUE TITLE
Add Unit tests for uncovered lines of code for Dag Deploy History

### ISSUE THREAD

**Issue by rujhan-arora-astronomer** [astronomer/astronomer#2269] opened 2024-07-30 20:25 UTC
Add Tests for https://github.com/astronomer/astro-ui/pull/1791

**Comment by danielhoherd** [comment] 2024-07-30 20:29
Duplicate of https://github.com/astronomer/issues/issues/6528

**Closed by danielhoherd** 2024-07-30 20:29 UTC
Labels: area/astro-ui
