### ISSUE TITLE
postgres grant statement fails with user@host:pw@host syntax

### ISSUE THREAD

**Issue by ghost** [astronomer/astronomer#1756] opened 2022-12-06 16:03 UTC
Deployment fails to become available.
Logs from Houston worker show:
```
INFO Creating database true_conjunction_1629_airflow
ERROR GRANT native_declination_1234_airflow TO admin_user@hostname - syntax error at or near "@"
```

The postgres connection string is fetched from the `astronomer-bootstrap` k8s secret in my setup.
I had to make it of the shape `postgres://user@host:password@host.postgres.database.azure.com:5432` because `postgres://user:password@host.postgres.database.azure.com:5432` would not work: the pods did not go healthy because they could not connect to the db server.

It should work if the postgres statement were:
`GRANT native_declination_1234_airflow TO "admin_user@hostname" `

## Environment

- astronomer v0.28.7
- airflow v2.1.4
- kubernetes v1.22.11
- Azure AKS managed cluster
- Azure Postgres Server

Please point me to the repo where I should post this issue if it is not in here.

**Comment by danielhoherd** [comment] 2022-12-06 16:11
@freek-hoekstra-cardano sorry, i replied to quickly last time. what version of postgres?

**Comment by freek-hoekstra-cardano** [comment] 2022-12-06 16:16
The postgres server is on postgres version 11

**Comment by danielhoherd** [comment] 2022-12-06 16:59
I found a GH issue where somebody else had this issue, and it was caused by them creating their postgres users with `user@host` username vs just `user` username. https://github.com/ckan/ckan/issues/6308#issuecomment-1184399014

**Comment by dbsanfte** [comment] 2022-12-06 22:27
Hi Daniel,

Azure Managed Postgresql servers always give their credentials in a `username@hostname` format. That being said we should be urlescaping the @ in the username. We'll try that first and circle back.

**Comment by freek-hoekstra-cardano** [comment] 2022-12-08 10:16
Tried several url-encoding options but the problem persists:
* replacing both `@` in the connection string with `%40`
* replacing only the `@` in the `user@hostname` part of the connection string with `%40`

Same logs with syntax error at or near "@"

**Comment by freek-hoekstra-cardano** [comment] 2022-12-08 10:45
In addition to the above, encoding only the second `@` sign (the one in front of hostname) results in the same stack trace as encoding both `@` signs in the connection strings.

So in conclusion:
* URL-encoding the second `@`-sign results in a new error earlier in the initialization process
* URL-encoding the first `@`-sign does not change behavior from the original issue.

FYI I am using Terraform in UTF-8 and the kubernetes Terraform module takes care of base64'ing

**Comment by freek-hoekstra-cardano** [comment] 2022-12-08 15:25
Any ideas @danielhoherd ?

**Comment by ashb** [comment] 2022-12-09 19:42
Can you confirm what value the secret is getting in the bootstrapper pod at runtime?

I think of anything is going to work out would be one of the form

`postgres://user%40host:password@host.postgres.database.azure.com:5432`

**Comment by danielhoherd** [comment] 2022-12-12 16:30
I suspect this is a problem with the way psycopg in db-bootstrapper connects. Microsoft's recommendations is to not use a `proto://user:pass@server` URI, and instead set up the connection with individual `k=v` pairs: https://learn.microsoft.com/en-us/azure/postgresql/single-server/connect-python#step-1-connect-and-insert-data

In db-bootstrapper, we... import the astronomer-bootstrap secret (which is a `proto://user:pass@host` string) into the env here <https://github.com/astronomer/astronomer/blob/283161a205/charts/astronomer/templates/houston/api/houston-deployment.yaml#L66-L70> then use that in psycopg here <https://github.com/astronomer/db-bootstrapper/blob/a7ae2a6af79b12575f46108de791776c49e2ba71/db_bootstrapper/main.py#L217> (see also lines 29 and 197)

If that is indeed the problem, though it could be one of several, we could modify db-bootstrapper to parse out the credentials and turn them into the string that Microsoft is demanding that we use.

**Comment by danielhoherd** [comment] 2022-12-12 21:04
I've reproduced the problem in sqlalchemy==1.3.24, which is what db-bootstrapper is currently limited to, 1.4.45, which is the latest stable, and 2.0.0b4, which is the latest beta.
```
>>> from sqlalchemy import create_engine
>>> url = 'postgresql://me:hunter2@localhost/test_db'
>>> engine = create_engine(url)
>>> engine
Engine(postgresql://me:***@localhost/test_db)
>>> conn = engine.url
>>> conn.database = "test_db"
>>> conn.username
'me'
```

**Comment by danielhoherd** [comment] 2022-12-12 21:26
I'm having a real hard time reproducing this problem locally. I've set up postgres 11 using docker-compose:
```yaml
version: '3'
services:
  database:
    image: 'postgres:11'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: hunter2
      POSTGRES_DB: test_db
```

Inside of a pgsql 11 console, I create a new user and grant it access:
```
$ psql postgresql://admin:hunter2@localhost/test_db
psql (11.18 (Debian 11.18-1.pgdg110+1), server 11.16 (Debian 11.16-1.pgdg90+1))
Type "help" for help.

test_db=# CREATE USER "me@example.com" WITH PASSWORD 'hunter2';
CREATE ROLE
test_db=# grant test_db to me@some_host
test_db-#
```

And in a python REPL I can parse the URL fine with sqlalchemy, and connect fine with psycopg2:

```
>>> from sqlalchemy import create_engine
>>> url = 'postgresql://me@some_host:hunter2@localhost/test_db'
>>> engine = create_engine(url)
>>> conn = engine.url
>>> conn.username
'me@some_host'
>>> import psycopg2
>>> c = psycopg2.connect(database='test_db', user=conn.username, password=conn.password, host=conn.host, port=conn.port)
>>> cur = c.cursor()
>>> cur.execute('select * from pg_stat_activity ;')
>>> for row in cur:
...     if row[1] == 'test_db':
...         print(f'{row=}')
...
row=(16384, 'test_db', 34, 10, 'admin', 'psql', None, None, None, None, None, None, None, None, None, None, None, None, '<insufficient privilege>', None)
row=(16384, 'test_db', 37, 16386, 'me@some_host', '', '172.19.0.1', None, 36458, datetime.datetime(2022, 12, 12, 21, 21, 9, 841050, tzinfo=datetime.timezone.utc), datetime.datetime(2022, 12, 12, 21, 22, 35, 633466, tzinfo=datetime.timezone.utc), datetime.datetime(2022, 12, 12, 21, 22, 35, 633749, tzinfo=datetime.timezone.utc), datetime.datetime(2022, 12, 12, 21, 22, 35, 633750, tzinfo=datetime.timezone.utc), None, None, 'active', None, '572', 'select * from pg_stat_activity ;', 'client backend')
>>>
```

**Comment by freek-hoekstra-cardano** [comment] 2023-02-02 16:12
FWIW, I have given up on this too and am now simply using a manually installed postgres in a VM, which works flawlessly with Astronomer with minimal setup

**Comment by danielhoherd** [comment] 2023-02-03 14:21
@freek-hoekstra-cardano thanks for checking back. I'm bummed we couldn't figure this out yet though. I'll leave it open for now.

**Comment by danielhoherd** [comment] 2023-02-22 20:30
@freek-hoekstra-cardano I just heard from one of our support folks that this credential format has only been observed in Azure Single Server, which is not a server that we support. Our docs are not clear enough about not supporting that, so I'm opening a ticket to improve that. Can you confirm whether or not that is the db server you are using?

**Comment by danielhoherd** [comment] 2024-04-22 19:32
Docs about not supporting azure single server were merged. Closing this.

**Closed by danielhoherd** 2024-04-22 19:32 UTC
Labels: kind/bug, team/platform
