### ISSUE TITLE
New system component: Necropolis 

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#287] opened 2019-04-02 18:54 UTC
Garbage collector for Astronomer platform

[Name inspiration](https://www.space.com/36602-space-junk-cleanup-concepts.html)

In order to maintain a tidy system, the Astronomer platform should be self-cleaning by default.

- [ ] Databases for deleted deployments
- [ ] Old Docker images
- [ ] More stuff (please edit/add to this list)!

**Comment by schnie** [comment] 2019-04-02 19:45
Dupe of https://github.com/astronomer/astronomer/issues/272. 

Copied name link over to the original issue. Closing this one.

**Closed by schnie** 2019-04-02 19:45 UTC
Labels: area/docker-registry, kind/feature, priority/important

**Comment by ryw** [comment] 2019-04-02 21:26
Ah i searched - didn't see it :)
