### ISSUE TITLE
Alertmanager can't use its data mount when using persistent volume

### ISSUE THREAD

**Issue by marekm-gain** [astronomer/astronomer#1043] opened 2021-03-24 12:30 UTC
When using data mount with values like below:
```yaml
    dataDir: "/data"
    persistence:
      enabled: true
      size: 2Gi
      storageClassName: longhorn
```
this dir is only accessible to root however alertmanager is running as nobody(65534). Therefore is not able to access it.

**Comment by rbankston** [comment] 2021-06-04 22:38
Hello @marekm-gain this is going to be fixed with the next release which includes https://github.com/astronomer/astronomer/pull/1109

**Comment by pgvishnuram** [comment] 2022-01-19 09:20
@marekm-gain - this issue is getting stalled , did you test the behaviour with our latest astronomer version.

**Comment by danielhoherd** [comment] 2022-03-23 23:49
Closing stale issue that has not had a response from the user since it was originally filed a year ago. The original report didn't include the version of astronomer they were using, but the problem is fixed in the latest version of Astronomer.

**Closed by danielhoherd** 2022-03-23 23:49 UTC
