### ISSUE TITLE
Data flipping 30 minutes bug is still present

### ISSUE THREAD

**Issue by ryw** [astronomer/astronomer#420] opened 2019-08-14 13:49 UTC
![2019-08-14 09 47 55](https://user-images.githubusercontent.com/4283/63026196-ba274700-be78-11e9-8e33-164d1a7a84f4.gif)

**Comment by ryw** [comment] 2019-08-14 13:57
Failure data flips too
![2019-08-14 09 47 55](https://user-images.githubusercontent.com/4283/63026877-ee4f3780-be79-11e9-92ac-7456102a77b9.gif)

**Comment by samblackk** [comment] 2019-08-14 13:58
Would you be open to visiting a different chart for this information?

**Comment by ryw** [comment] 2019-08-15 18:18
I think we should just fix it where it is - I can look at it again if you'd like.

**Comment by samblackk** [comment] 2019-08-21 20:36
This is next up on my list.

**Comment by samblackk** [comment] 2019-08-30 14:17
![](https://github.trello.services/images/mini-trello-icon.png) [Data flipping 30 minutes bug is still present](https://trello.com/c/DAWPSIIo/3-data-flipping-30-minutes-bug-is-still-present)

**Comment by schnie** [comment] 2019-09-05 19:37
@samblackk we're trying to ship v0.10.1 ASAP to put on new cloud. Do you think we can squeeze this in or should we push it out to v0.10.2?

**Comment by samblackk** [comment] 2019-09-05 19:38
@schnie push to v0.10.2 - I'm still working through finding the root cause of this - it doesn't happen all the time while I'm testing.

**Comment by schnie** [comment] 2019-09-13 14:17
@samblackk fixed this with a stacked line chart ^^. This is merged for v0.10.1 :tada:

**Closed by schnie** 2019-09-13 14:17 UTC
Labels: area/monitoring, area/orbit-ui, kind/bug
