### ISSUE TITLE
Airflow RBAC issues

### ISSUE THREAD

**Issue by schnie** [astronomer/astronomer#353] opened 2019-07-01 19:26 UTC
Couple issues that came up with the latest release, mostly around RBAC:

- [x] Airflow: Can't mark dag runs as succeeded
No roles (Viewer, Editor, Admin) can mark dag runs as succeeded in the UI. Attempting to do so results in "Access Denied".

- [x] Airflow: search box usability is broken
In the previous version of Airflow, if I typed "PRD" into the search bar, it would return all Production DAGs in that deployment (pattern matching). Now, if you type "PRD" it will return 0 results. You need to specify the exact dag name. Is there any way this "improvement" can be disabled? Quite often we are interested in looking at the status of groups of dags that follow a particular convention, and it appears that we've lost this ability in the latest version of Airflow.

- [x] Airflow: Access denied when attempting to view your profile
Checking your profile takes you to "You do not have permission to view this page". This doesn't seem like expected behaviour.

- [x] Airflow: task log does not filter by the attempt
Previously, if you opened a dag run you would be presented with links ("1 2 3 4 5...") that correspond to the attempts of that particular run. These links still exist but appear to be unfiltered: they all render the entire log (all attempts).

**Comment by schnie** [comment] 2019-07-01 19:33
@ashb had a report of these issues from a customer. Think you could take a look at these?

**Comment by ashb** [comment] 2019-07-02 10:22
> Airflow: search box usability is broken

Fixed in 1.10.4rc2

**Comment by ashb** [comment] 2019-07-02 11:03
> Airflow: Access denied when attempting to view your profile

Still an issue in 1.10.4. We can patch-up locally.

**Comment by ashb** [comment] 2019-07-02 15:10
> Airflow: Can't mark dag runs as succeeded

Confirmed, missing the `can_dagrun_success` permission. Same applies for dagrun failed. dag cleared works though. Can be patched locally in our FAB security manager until fixed in Airflow.

**Comment by ashb** [comment] 2019-07-02 15:45
> Airflow: task log does not filter by the attempt

Cannot reproduce locally. I'll need to speak to the customer to dig in to this one more.

**Comment by vparekh94** [comment] 2019-07-02 15:52
Setting up time to chat these through with the customer as soon as we can. Thanks for looking into these @ashb

**Comment by schnie** [comment] 2019-07-02 18:47
@ashb thanks for digging into these! For the profile one, would that be a fix on our fork that we'd contribute back or something in our security manager?

**Comment by ashb** [comment] 2019-07-02 21:45
Both - contribute back, but can fix in our Security Manager so we don't have to wait for Airflow 1.10.5 or 2.0.0 to be released.

**Comment by schnie** [comment] 2019-07-17 14:53
@ashb realized this got closed with automation. Should we keep it open or is there one more we need to do something for?

**Comment by ashb** [comment] 2019-07-17 15:18
The only outstanding issue is "Airflow: task log does not filter by the attempt" which I couldn't reproduce, and was waiting to speak to the customer on.

**Comment by ashb** [comment] 2019-07-18 10:17
I didn't fix point 1 correctly for deployed clusters (only for local DB users) - will re-open and apply a new fix against our Security manager

**Closed** 2019-07-18 13:44 UTC
Labels: area/airflow, kind/bug, priority/important
